---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(randomForest)
library(caret)
```
# 1. colon 데이터에 랜덤 포리스트를 적용하는데, k-겹 교차 검증을 k를 5,10,15,20으로 바꾸면서 적용하라. 각각의 혼동 행렬과 정확률을 제시하라.

```{r}
head(colon)
set.seed(2021)
clean_colon <- na.omit(colon)
data <- clean_colon[sample(nrow(clean_colon)),]
data$status <- as.factor(data$status)
options(digits = 4)

for(a in seq(5,20,5)) {
    k <- a
    q <- nrow(data) / k
    l <- 1:nrow(data)
    accuracy <- 0
    for (i in 1:k) {
        test_list <- ((i-1)*q+1) : (i*q)
        data_test <- data[test_list,]
        data_train <- data[-test_list,]
        rf <- randomForest(status~., data_train)    
        pred <- predict(rf, data_test, type = 'class')
        t[k/5] <- table(pred, data_test$status)
    }
    accuracy[k/5] <- accuracy + (t[1,1]+t[2,2])/nrow(data_test)
}
t[1]
accuracy[1]

t[2]
accuracy[2]

t[3]
accuracy[3]

t[4]
accuracy[4]

t[5]
accuracy[5]
```

# 2. UCLA admission 데이터에 대해 수행
```{r}
ucla <- read.csv('https://stats.idre.ucla.edu/stat/data/binary.csv')
ucla$admit <- factor(ucla$admit)

control <- trainControl(method='cv', number=5)
dt <- train(admit~., data=ucla, method='rpart',
            metric='Accuracy', trControl=control)
rf <- train(admit~., data=ucla, method='rf',
            metric='Accuracy', trControl=control)
sv <- train(admit~., data=ucla, method='svmRadial',
            metric='Accuracy', trControl=control)
kn <- train(admit~., data=ucla, method='knn',
            metric='Accuracy', trControl=control)

resamp <- resamples(list(결정트리=dt, 랜덤포레스트=rf,
                             SVM=sv, KNN=kn))
summary(resamp)
sort(resamp, decreasing=T)
```

# 3. voice 데이터에 대해 수행
```{r}
voice <- read.csv("C:/workspace/r/data/voice.csv", header = TRUE)
voice$label <- factor(voice$label)
str(voice)

control <- trainControl(method='cv', number=5)
dt <- train(label~., data=voice, method='rpart',
            metric='Accuracy', trControl=control)
rf <- train(label~., data=voice, method='rf',
            metric='Accuracy', trControl=control)
sv <- train(label~., data=voice, method='svmRadial',
            metric='Accuracy', trControl=control)
kn <- train(label~., data=voice, method='knn',
            metric='Accuracy', trControl=control)

resamp <- resamples(list(결정트리=dt, 랜덤포레스트=rf,
                             SVM=sv, KNN=kn))
summary(resamp)
sort(resamp, decreasing=T)
```

