---
title: "분류"
author: "kim"
date: '2021 5 3 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ucla 데이터
## 1. DT(decision tree)
```{r}
library(rpart)
library(caret)
library(randomForest)
library(e1071)
library(class)
ucla <- read.csv('https://stats.idre.ucla.edu/stat/data/binary.csv')
str(ucla)
ucla$admit <- as.factor(ucla$admit)
str(ucla)

train_index <- createDataPartition(ucla$admit, p=0.8,list=F)
ucla_train <- ucla[train_index,]
ucla_test <- ucla[-train_index,]

# 모델링/학습
dtc <- rpart(admit ~ ., ucla_train)

# 예측
pred <- predict(dtc, ucla_test, type='class')
table(pred)

# 평가
confusionMatrix(pred, ucla_test$admit) 
```

## 2. RF(Random Forest)
```{r}
train_index <- createDataPartition(ucla$admit, p=0.8,list=F)
ucla_train <- ucla[train_index,]
ucla_test <- ucla[-train_index,]

# 모델링/학습
rf <- randomForest(admit ~., ucla_train)

# 예측
pred <- predict(rf, ucla_test, type='class')

# 평가
confusionMatrix(pred, ucla_test$admit)

```

## 3. SVM(Support vector Machine)
```{r}
train_index <- createDataPartition(ucla$admit, p=0.8,list=F)
ucla_train <- ucla[train_index,]
ucla_test <- ucla[-train_index,]

# 모델링/학습
svc <- svm(admit~., ucla_train)

# 예측
pred <- predict(svc, ucla_test, type='class')

# 평가
confusionMatrix(pred, ucla_test$admit)

```

## 4. K-NN(k-Nearest Neighbor)
```{r}
train_index <- createDataPartition(ucla$admit, p=0.8,list=F)
ucla_train <- ucla[train_index,]
ucla_test <- ucla[-train_index,]
# 모델링
k <- knn(ucla_train[,2:4],ucla_test[,2:4],
         ucla_train$admit, k=5)
confusionMatrix(k, ucla_test$admit)
```

# wine 데이터
```{r}
wine <- read.table('C:/workspace/r/data/wine.data.txt', sep=',')
columns <- readLines('C:/workspace/r/data/wine.name.txt')
names(wine)[2:14] <- columns
names(wine)[2:14] <- substr(columns,4,nchar(columns))
names(wine)[1] <- 'Y'
wine$Y <- as.factor(wine$Y)
train_index <- createDataPartition(wine$Y, p=0.8,list=F)
wine_train <- wine[train_index,]
wine_test <- wine[-train_index,]

```

## 1. DT(decision tree)
```{r}
# 모델링/학습
dtc <- rpart(Y ~ ., wine_train)

# 예측
pred <- predict(dtc, wine_test, type='class')
table(pred)

# 평가
confusionMatrix(pred, wine_test$Y) 
```

## 2. RF(Random Forest)
```{r}
# 모델링/학습
rf_wine <- randomForest(Y ~., wine_train)

# 예측
pred <- predict(rf_wine, wine_test, type='class')

# 평가
confusionMatrix(pred, wine_test$Y)

```





