---
title: "chapter 6 - test"
author: "kim"
date: '2021 4 27 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder)
library(ggplot2)
library(dplyr)
```
# 단원문제 1. gapminder 데이터에 기록된 전 세계 인구의 구성 비율은 어떻게 변화하고 있을까?
### 1) 전체 관측 기간(1952년~2007년) 중 1952년도의 인구 구성을 추출한 후 시각화하라.
```{r}
x <- gapminder %>%
      filter(year==1952) %>%
      select(continent,pop) %>%
      head()
pie(x$pop,x$continent)
barplot(x$pop, names.arg = x$continent)
```

### 2) 1952년~2007년의 인구 구성을 for문을 이용해 반복적으로 시각화하라.
```{r}
for (i in seq(1952,2007,by=5) ){
      x <- gapminder %>%
      filter(year==i) %>%
      select(continent,pop) %>%
      head()
      barplot(x$pop, names.arg = x$continent)
      }

```

### 3) 시각화 그래프를 통해 알게 된 사실을 몇 가지로 요약하라.
1. 아메리카와 아프리카 대륙의 인구수가 가장 많다.

# 2. ggplot2를 이용하여 Iris 데이터 셋에 대해서 다음 문제를 푸세요.
### 1) 품종별로 Sepal/Petal의 Length, Width 산점도 그리기. (총 6개)
```{r}
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width,col=Species)) +
      geom_point()
ggplot(iris, aes(x=Sepal.Length, y=Petal.Length,col=Species)) +
      geom_point()
ggplot(iris, aes(x=Sepal.Length, y=Petal.Width,col=Species)) +
      geom_point()
ggplot(iris, aes(x=Sepal.Width, y=Petal.Length,col=Species)) +
      geom_point()
ggplot(iris, aes(x=Sepal.Width, y=Petal.Width,col=Species)) +
      geom_point()
ggplot(iris, aes(x=Petal.Length, y=Petal.Width,col=Species)) +
      geom_point()
```

### 2) 품종별 Sepal/Petal의 Length/Width 평균을 비교하되
### 항목을 옆으로 늘어놓은 것(beside=T)과 위로 쌓아올린 것 2개를 그리시오. 
### (총 12개 항목의 데이터를 2개의 그래프에)
```{r}
iris_avg <- iris %>%
      group_by(Species) %>%
      summarise(SepalL_avg=mean(Sepal.Length))
iris_avg
```



### 3) 박스 플롯 그리기
```{r}

```

